### ISSUE TITLE
名称変更依頼

### ISSUE THREAD

**Issue by miramiku** [yukky-t/Laurus#3]
「改変」という言葉は印象が悪いので
Laurus Improved または Improved Laurus という名前に変更お願いします（前後どちらにつけても構いません）。Improved は改良したという意味になります。
Credit, Changelog などでも「改変」という言葉を用いず「改良」または「Improved」という言葉に変更お願いしますー。

**Comment by yukyt** [comment]
了解ですー。
副作用ありで機能追加したので、一概に改”良”と言い切ってしまうのが抵抗があったので
こういう名前にしましたが、確かにちょっと言葉のイメージは良くなかったかもです。
変更しておきます。

**Comment by miramiku** [comment]
とんでもない。機能補強していただいてるんですから改"良"ですー！
（私の身辺が）落ち着き次第、リンク張らさせていただきますー

**Comment by yukyt** [comment]
取り急ぎ修正しました！
落ち着いてからで全然かまわないのでご確認お願いします

**Comment by miramiku** [comment]
ありがとうございますー＞＜；
お手数おかけしますー

**Comment by miramiku** [comment]
Cheatsheet だけボックスサイズの関係ではみでてますが・・・まぁ支障はないでしょう
確認しました！ありがとうございますー！
マージしたら、名前をこっちに変えちゃいましょう＞＜；

Laurus Improved かっこいいです＞＜；気にっちゃいました＞＜；

![default](https://user-images.githubusercontent.com/1246535/36946643-0c109168-2003-11e8-8cf9-5d55835156e0.PNG)

**Comment by yukyt** [comment]
wordrobeだけ確認して満足してましたm(_ _)m
スペースはだいぶ切り詰めちゃったので、これ以上はcssいじらないとですね
名前気に入ってもらえてよかったです！
