### ISSUE TITLE
ドキュメントの不備について

### ISSUE THREAD

**Issue by miramiku** [yukky-t/Laurus#4]
Laurus のドキュメントやその他、補助ツールの不備に関しては誠に整備が整っておらず申し訳ございません。
なにかアルゴリズム、コード、その他、分からない点、気になってんがあればなんなりとお問い合わせください。

**Comment by yukyt** [comment]
ありがとうございます(｀･ω･´)ゞ
今のところ気になってるのは以下３点です
１．jsのコンパイルのコマンド。
　　今のところ未コンパイルで個別に読ませてます。
２．lessのコンパイルのコマンド。
　　いまのところ下記のコマンドでやってます。
　　`lessc features/theme.less theme.css  -x`
３．想定してる対象環境
　　アロー関数とか使ったので、旧型IEとかで動かなくなってると思います

**Comment by miramiku** [comment]
気になる点についてお答えします

1.  jsのコンパイルのコマンド
    * 現状 VSCode と gulp で処理しています。minifyしているだけですね…
1.  lessのコンパイルのコマンド
    * lessも同様にgulpでやっていますが、theme.lessだけコンパイルするだけで ok です。そのコマンドで問題ないと思います
1. 対象環境について
    * 私自身、不勉強なところが多いのでES2016について分かりません…旧型IEの心配はおそらく不要だと思われます。現状、モバイル：パソコン：タブレット＝60：25：15といった割合で、IEを使われている人は全体の5%未満にすぎません。またバージョンも11のみでした（この1週間のアクセス記録による）。そのため、旧型IEに関して心配は無用だと考えられます

**Comment by yukyt** [comment]
回答ありがとうございます。
1.2 了解です。
3.確認したらIE全滅でした
https://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/arrow_functions#Browser_compatibility
旧式のスマホ使われてる方のChromeバージョンも不安ですし、
やはりbabelなしでES2015↑を使うのは不利益大きそうです。
かと言って、これだけのためにbabel入れるのは手間のほうが大きいので、従来の書き方に置換します。

**Comment by yukyt** [comment]
リセットや編集ロックで使われているアイコンフォント使いたいのですが、
Creditに表記のあるフォントのどちらを使われてますでしょうか？
表示モード切り替えでFont awesomeでいうところのuserとusersみたいなのを使おうと思ってます。

**Comment by miramiku** [comment]
基本的にこだわってないんですよねー…。
関係ないですが英文の Maven Pro だけでアイコンフォントはコンセプトにあったのをかいつまんでるだけですー。なのでオムニバス４つのアイコンフォントが混ざってるんですよね…

**Comment by yukyt** [comment]
こんな遅くにありがとうございます
恥ずかしながら、普段自分で使うときはCDNにリンク貼って使ってるのでwoffファイル見る場合の使い方がよくわからず…
混じっているということはビューアで中を見ないとどのコードに割り当てられているかわからない感じでしょうか？

**Comment by miramiku** [comment]
↓こちらのサイトを利用させていただいております
https://icomoon.io/

IcoMoon Appというものを…
そちらで Import Icons でsvg ファイルを読み込んでいただければ大丈夫だと思いますー！
unicode の私的領域使うと W3C Validator に怒られるので、既存のコードを代替してる感じですね…

**Comment by yukyt** [comment]
わかりました！ ありがとうございます！
importして使いたいの追加してexportする形でやってみます。

**Comment by miramiku** [comment]
分かりにくくてすみません…
お願いします―＞＜；

**Comment by yukyt** [comment]
手こずったけどできました！
ありがとうございますm(_ _)m

**Comment by yukyt** [comment]
こちらも解決したので閉じます！
