### ISSUE TITLE
本家の推奨コーデ表示形式との互換モード実装

### ISSUE THREAD

**Issue by yukyt** [yukky-t/Laurus#5]
こちらの仕様は本家に比べて以下のデメリットがあるので、
モード選択できるようにしてユーザが選択できるようにしたい

1.縦に長くなる
推奨コーデ表示部分は約２倍になるので、一覧性の低下とスクロール量増加
アイテムコンプに近いような人はこのデメリットが大きいと思われる

2.横に長くなる
900px -> 958px
あまり実害はなさそうだが、スマホユーザには使い勝手低下するかもしれない

3.非所持衣装を含めて計算することによるパフォーマンスの低下
実際の計算量は調べてないので、低下なしあるいは誤差範囲の可能性も結構ある

**Comment by miramiku** [comment]
非所持アイテム機能はおまけ扱いなのであまり重要視していませんでした。入手不可能になってしまったイベントアイテムや当分先のマンスリーサインアップコーデアイテム、一生シリーズなど上位にでてくるが入手してないものを非表示にすることを想定としていました。毎日数個ずつ入手している現状なので（入手０の日もありますが…）、あまり厳格に管理するのは大変だと感じていたので…

計算量に関してはO(N)ですね。なのでJIT型のJSエンジン搭載のモダンブラウザならばパフォーマンスの低下はほぼないと考えられます。

**Comment by yukyt** [comment]
私もあまり厳密な管理をするつもりはありませんでした。
つい先日13章クリアした位の状況なので、スコア見直しする機会が多かったために
ハイスコア見直しが少しでも楽になればと。

計算量についても了解です。

**Comment by miramiku** [comment]
コーデ組み立て用と見直し用の配置替えとかやりたいんですけどね…
めんどくさくて止まってます。あといくつか改良を予定していますが、コードの根幹にも影響する可能性がある改良のでしばらくこちら側の侵襲性が高いコードの変更は後回しまたは一時保留にしておきますね。

**Comment by yukyt** [comment]
お気遣いありがとうございます。
私も3月15日まではあまり動けないかもですが、
遅くとも今月中にはissue片付けてプルリク出すくらいのつもりです(｀･ω･´)ゞ

**Comment by yukyt** [comment]
モードチェンジ自体は実装。以下懸案。
１．エリアの幅指定がそのままなので折返しされてないのを直す
２．モード自体はローカルストレージあたりで覚えさせて、ユーザ毎にデフォルト設定を固定する
３．Advisorの全体幅が980pxになったのは、最悪固定でもよさそう
明日もがんばるぞい٩( 'ω' )و

**Comment by yukyt** [comment]
１．修正
２．修正
３．ひとまずそのまま
追加で
４．複数表示モードは非所持アイテムも含めて見せるが、本家の単一表示は所持アイテムのみなので、モード切り替え時にMedium.recommend.initを呼び直して初期化する処理を追加

**Comment by miramiku** [comment]
お疲れさまでした＞＜；

ひとまずプルリクの内容確認の上マージしますね！
あとは Changelog やバージョンなどのうちのほうの作業もできるときに（今日中）
