### ISSUE TITLE
データベースについて

### ISSUE THREAD

**Issue by miramiku** [yukky-t/Laurus#7]
`laurus.js` 内で読み込むデータベース `features/wardrobe.json` と `features/stages.json` を私のほうのリポジトリから直リンクに変更して頂くとただいた方がいいかもしれません…。（Changelogは放置で…）
あと、今回のイベントでついに SSS が登場してしまいましたので、あらかじめ考慮して製作していましたが不要な処理なので搭載していませんでした…。

https://github.com/miramiku/Laurus/commit/46999a14f1794c83937e3210c5b8799d729d6f8c

上記を参考に `laurus.js` に３行追加、`LAURUS.STATIC_ITEMS` の `_values`  内のみですね。記載お願いします。また、`features/style-common.less` 内も `.attributes-SSS` というクラスの色指定もついでにお願いします（２か所）。お手数おかけして申し訳ありません。

また、私の Laurus のほうにアレンティーさんの Improved 版 Laurus へのリンクをページ下部及び Credit 内に追加しましたので一度ご確認いただければ幸いです。

**Comment by yukyt** [comment]
ちょうどrebaseしようとしてぶつかってたところでした！
ありがとうございます。
確定申告でバタバタしてますが、土日の間に取り込めると思います。

**Comment by miramiku** [comment]
ごゆっくり焦らずどうぞ～＞＜；
何か気になった点があればなんなりと。

**Comment by yukyt** [comment]
1.11.0取り込みました！

衣装/ステージデータについてはこちらで触ることはなく、
mergeで簡単に取り込めるため一旦このままでいいかなと思います。
（衣装更新あと1,2回の間に完成までいけそうですし）

わざわざリンクとクレジット表記ありがとうございますm(_ _)m 確認しました。

**Comment by miramiku** [comment]
はやい！おつかれさまですー！

wardrobe/stage は結構頻繁にいじるので頻繁にマージする必要もないと思いますが…
データに重大なミスなどが発覚したときはご了承を；；

ニキの前のゲーム（サービス終了済み）ではデータベースだけ Dropbox にいれてそこから読み込んでました…今、コミット数稼ぎ (ｺﾞﾎｺﾞﾎ) のために同包しちゃってますー。

この Issue クローズですー
